### ISSUE TITLE
Add github metafiles

### ISSUE THREAD

**Issue by ErinCall** [pelotech/drone-helm3#12]
Github repos can provide configuration with some special files. README.md is the most prominent, but there are several others that may be useful here:

* [`CODEOWNERS` automatically adds reviewers to PRs](https://help.github.com/en/github/creating-cloning-and-archiving-repositories/about-code-owners). I'd like it to have at least one person other than myself; @josmo @kav @grinnellian any volunteers?
* [pull request and issue templates will prepopulate PR and issue bodies, respectively](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates). Offhand I don't know of anything we'd definitely want in those files, but maybe someone else does?
* [`CONTRIBUTING.md` tells people about workflow guidelines](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors) (e.g. "all pull requests should be linked to an issue"). I have Opinions about how git commits should be structured, but I won't try to impose them unless someone says "yeah, let's consider rules about branches and commits".
  * This overlaps with the "notes for contributors" note in #8.
* [`CODE_OF_CONDUCT.md` tells people about un/acceptable behavior](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project). I suggest the Contributor Covenant.

Let's put one or more such files in a `.github/` folder.

**Comment by grinnellian** [comment]
Happy to be in PR groups

**Comment by ErinCall** [comment]
@josmo The Contributor Covenant includes a section that says "Instances of [...] unacceptable behavior may be reported by contacting the project team at _____". What's an appropriate email address to use there?
