### ISSUE TITLE
Choose a license

### ISSUE THREAD

**Issue by ErinCall** [pelotech/drone-helm3#23]
GPLv3 is my goto, but Joachim has concerns about whether it's appropriate. Let's reach agreement on one.

**Comment by grinnellian** [comment]
@josmo What concerns?

MIT is a decent fallback for anything you want to get broad uptake on.
I love the idea of viral licenses but they do unfortunately limit adoption. For good reason from a corporate incentives standpoint.

**Comment by ErinCall** [comment]
After reading some "what license should I use" articles I think Apache seems right. I don't think GPL would limit adoption that much since this isn't library code, but the viral-license part wouldn't do much either for the same reason. 

(Apparently GPL also requires putting copyright information in every file and keeping it up to date, and I'd rather not deal with the hassle)

**Comment by grinnellian** [comment]
Just out of curiosity what made you prefer Apache to MIT?

**Comment by ErinCall** [comment]
@grinnellian apparently it’s more appropriate than MIT for company-owned code because the liability and patentability provisions are more explicit. I’m not sure how much of that is “it’s an important consideration for companies” vs. “it will appease a large corporation’s lawyers,” but since they’re roughly equivalent I figure it doesn’t hurt.
