### ISSUE TITLE
Add a keep_history setting for Delete

### ISSUE THREAD

**Issue by ErinCall** [pelotech/drone-helm3#24]
helm2's `delete` command had a `--purge` option that would purge Helm's release ledger. In helm3 that behavior is the default; if you want to keep the ledger you need to supply `--keep-history`. 

I'm not sure whether this should be on by default. 

On the one hand, drone-helm had a `purge` setting, but it doesn't appear to be functional (it's omitted from the code that loads env vars into the config). So anything that was using delete was getting the non-purge behavior. If we want drone-helm3 to be fully backwards-compatible with drone-helm, our keep_history setting should default to `true`. 

However, the fact that Helm 3 made purging the default behavior means "don't keep history" is probably the appropriate default in general. In that case we should follow their lead and make our keep_history default to `false`.

If we decide to make `false` the default, remove this issue from the Version 1.0 milestone.

**Comment by josmo** [comment]
I'd say default delete with purge of helm3 and if someone wants to PR keep history they can
