### ISSUE TITLE
Deal with the change in helm's --timeout flag

### ISSUE THREAD

**Issue by ErinCall** [pelotech/drone-helm3#39]
**The problem I'm trying to solve:**
helm2's `--timeout` flag specified a number of seconds for the timeout. In helm3 it uses a string formatted for [golang's `ParseDuration` function](https://golang.org/pkg/time/#ParseDuration), e.g. "200s".

If someone is upgrading from drone-helm and they have a `timeout: 200` in their settings, it won't do what they expect. I'm not sure whether helm will just exit with an error or set the timeout to 0, but either way the deployment won't succeed.

**How I imagine it working:**
I see two options:

1. Say "update your timeout setting" in the "Upgrading from drone-helm" section of the readme
1. If we see a bare number in cfg.Timeout, append an `s` so it means the same thing it did in helm2

**Comment by josmo** [comment]
I personally say lets go with option 2, it will make converting simpler for folks
