### ISSUE TITLE
Tooling: CI builds and image-publishing

### ISSUE THREAD

**Issue by ErinCall** [pelotech/drone-helm3#7]
* Add this repository to https://drone.pelo.tech/
* Configure `.drone.yml` to run the `test` and `lint` steps for new PRs
* Configure `.drone.yml` to publish an image to docker hub when a PR is merged
* Add branch protection to `master` that requires CI to pass before merging a PR

**Comment by ErinCall** [comment]
If #8 has already been done, we'll need to update the example `.drone.yml` stanza in `README.md` so it shows the actual plugin image.

**Comment by ErinCall** [comment]
@josmo I've assigned this issue to you because I don't have sufficient perms to complete it—I can't activate repos on drone.pelo.tech and I can't set branch protections on this repo.

**Comment by josmo** [comment]
protected master and builds/publish in place

**Comment by ErinCall** [comment]
* √ Added to our Drone server
* √ Image is published as [pelotech/drone-helm3](https://hub.docker.com/repository/docker/pelotech/drone-helm3)
* √ Drone config was done in 6452a01
* √ Branch protection added
