### ISSUE TITLE
Can't find path for Chart, and error kube_api_server doesn't display error message

### ISSUE THREAD

**Issue by kyle1739** [pelotech/drone-helm3#72]
**What happened:**

Drone can't find path for Chart, I think drone went directly to find the path inside the container,bacause i setting wrong KUBE_API,but the drone shows that the path cannot be found, instead it can't connect to the KUBE_API_SERVER.
**More info:**

    name: helm-deploy
    image: pelotech/drone-helm3
    environment:
      api_server: http://masterIP:6443
      kube_token:
        from_secret: dev_kubernetes_token
    settings:
      skip_tls_verify: true
      mode: upgrade
      chart: ./helm
      release: myapp
      wait_for_upgrade: true
      service_account: admin-user
      valuesi_fiies: ["/helm/myapp.yaml"]
      namespace: myapp
    trigger:
      event:
      - tag
      branch:
      - master

**Comment by ErinCall** [comment]
Will you paste the output from the Drone logs? If you can add `debug: true`, that would be especially helpful. It won't reveal secrets in this case--[the kube_token gets redacted](https://github.com/pelotech/drone-helm3/blob/master/internal/helm/config.go#L101).

**Comment by kyle1739** [comment]
I successfully pushed the chart to the harbor,
but when pulling the chart, it passes 443. Because it is a development environment, I don’t want to use https. Is there a way to pull the chart via http?

     calling *run.InitKube.Prepare (step 0)
     --
     3 | loading kubeconfig template from /root/.kube/config.tpl
     4 | creating kubeconfig file at /root/.kube/config
     5 | calling *run.AddRepo.Prepare (step 1)
     6 | Generated command: '/usr/bin/helm --namespace mml-dev --debug repo add mychart  http://192.168.20.172/chartrepo/helm-repo'
     7 | calling *run.Upgrade.Prepare (step 2)
     8 | Generated command: '/usr/bin/helm --namespace mml-dev --debug upgrade --install --wait --set image.tag=# mml mychart/mml'
     9 | calling *run.InitKube.Execute (step 0)
     10 | writing kubeconfig file to /root/.kube/config
     11 | calling *run.AddRepo.Execute (step 1)
     12 | "mychart" has been added to your repositories
     13 | calling *run.Upgrade.Execute (step 2)
     14 | Error: Get https://192.168.20.172/chartrepo/helm-repo/charts/mml-0.1.0.tgz: dial tcp 192.168.20.172:443: connect: connection refused
     15 | helm.go:76: [debug] Get https://192.168.20.172/chartrepo/helm-repo/charts/mml-0.1.0.tgz: dial tcp 192.168.20.172:443: connect: connection refused
     16 | while executing *run.Upgrade step: exit status 1

**Comment by ErinCall** [comment]
Thanks for that debug output. From what I can see, the http->https change is being made by helm itself, not by this plugin. Do the generated commands work if you run them from the command line?

We just created #75, adding a `repo_ca_file` setting, which might work for you. You'd still have to set up TLS, but you could use a self-signed CA certificate rather than having to get a certificate from a public CA.

**Comment by ErinCall** [comment]
@kyle1739 hi, just checking in—are you still looking for help with this?

**Comment by kyle1739** [comment]
Hi, when using a self-signed CA certificate, I still receive an error message stating that it is not a public CA certified certificate, so when I use the chartmuseum chart instead of https. 
thanks!!

**Comment by ErinCall** [comment]
Ok, sounds like you're all set, then :)
