### ISSUE TITLE
include a --ca-file to helm3 plugin

### ISSUE THREAD

**Issue by alexismaior** [pelotech/drone-helm3#74]
**The problem I'm trying to solve:**
It will be great to have a ca-file parameter in "helm repo add" for those who have a self-signed certificate in local repository (such as harbor).
Usually, I have to add a repo using the command "helm repo add my_repo https://my_repo.internal --ca-file ca.crt" 

**How I imagine it working:**
Create a "ca-file" parameter to read from secret, for example.

steps:
- name: deploy
  image: pelotech/drone-helm3
  settings:
    helm_command: upgrade
    namespace: staging
    add_repos: harbor=https://my_repo
    **ca-file:** 
         from_secret: REPO_CA
(...)

Thanks!

**Comment by ErinCall** [comment]
Sure, that should be no problem. Barring unforeseen mishaps, we can have it ready for you on Monday 🙂 

The setting will probably be `repo_ca_file`, to avoid confusion with the Kube cluster’s CA.

**Comment by alexismaior** [comment]
Amazing, Erin. I can't wait to test it. Thanks a lot! Great plugin, btw...

**Comment by ErinCall** [comment]
@alexismaior Ok, that setting is available in version 0.12.0. Let me know how it works for you!

**Comment by alexismaior** [comment]
Worked perfectly, Erin. Thanks a lot. As the "ca-file" parameter expects a "file", I had to mount the volume to pass the ca.crt locally. I don't know if there is a better way to do that but worked.

**Comment by josmo** [comment]
@ErinCall what would you think of taking the value from the ENV var and writing it to a file and then using that? it would allow for secrets to be injected in that way as well without mounting and seems more usable. :)

**Comment by ErinCall** [comment]
Ooh, yeah that does seem more usable. Might be worthwhile to throw in a `repo_certificate` setting too.

**Comment by ErinCall** [comment]
@alexismaior I've just opened #76, which _replaces_ the filepath setting with base64-encoded contents settings. Will it be a headache for you to switch your `.drone.yml` to match?

**Comment by ErinCall** [comment]
@alexismaior yay, I'm glad it worked for you! That update is now live in version 0.13.0 :)
