### ISSUE TITLE
Add build_dependencies parameter

### ISSUE THREAD

**Issue by obukhov** [pelotech/drone-helm3#85]
**The problem I'm trying to solve:**
To have reproducible builds it would be nice to have the option to install dependencies from Chart.lock.

**How I imagine it working:**
There is an option "update_dependencies" which can be used to avoid including dependencies in the source code. But this operation pulls a new version of dependencies according to Chart.yaml ranges.
This one runs `helm dependency update`, I can imagine another one would run `helm dependency build`

**Comment by josmo** [comment]
Thanks for the suggestion @obukhov - 

since I don't see much reason for having both update_dependencies and build_dependencies, it might be worth changing the settings interface to just dependencies: build or dependencies: update for each situation.

I'll take a look when I get some time otherwise I'm definitely open to a PR if you want to take a stab at it :)

**Comment by obukhov** [comment]
> I don't see much reason for having both update_dependencies and build_dependencies
Yeah, I agree they should be exclusive, I was thinking of having priority on Update or throwing an error if both are configured.

> worth changing the settings interface to just dependencies: build or dependencies: update
To be honest I don't have a clear understanding of how that should work. The change should be backward compatible, so it should be either new property (and then it is not so beneficial compared to build_dependencies parameter) or the type should be overloaded as "bool | string" which is even worse because it will be "update_dependency: build". The third option would be to have a separate operation for that (and it went different way already in the codebase). What do you think?

> I'll take a look when I get some time otherwise I'm definitely open to a PR if you want to take a stab at it :)
It would be interesting for me to do this change, I checked out the source already and it seems pretty straight-forward. If we agree on one solution, I can submit a pull request and we can discuss it further.

**Comment by josmo** [comment]
Thanks for being willing to contribute:  Here's what I was thinking for the implementation to backward support but deprecate update_dependencies.

1. I'd say lets keep update_dependencies: but mark it as deprecated:
2. Add settings property called dependencies_action: <string> [update or build]
3. If update_dependencies: true and dependencies_action set, exit with error stating update_dependencies is deprecated and is not supported with dependencies_action

Totally open on a different property name for the dependencies_action if something else is more clear.

Let me know how that sounds to you. Later on we can remove update_dependencies in a later version :)

**Comment by obukhov** [comment]
Sounds reasonable, I'll open a PR when it's ready :)

**Comment by obukhov** [comment]
@josmo I've added the pull request, please have a look when you have time

**Comment by josmo** [comment]
Thanks a ton @obukhov ! I just merged it in so it should show up in latest soon.  Want to comment on here once you've tried latest and I'll tag a new version?
