### ISSUE TITLE
Does it support publishing of the Helm charts?

### ISSUE THREAD

**Issue by sherry-ummen** [pelotech/drone-helm3#87]
Hi, Does it support publishing helm charts to some public repository example Azure Container Registry?

**Comment by josmo** [comment]
@sherry-ummen currently this plugging it for deploying helm charts using helm3 to k8s clusters not publishing the charts themselves to a charts registry if that's what you're asking :)

**Comment by sherry-ummen** [comment]
Yes that’s what I was asking 🙂 , do you happen to know any such drone plugin which could be used for publishing to registry?

**Comment by josmo** [comment]
Sadly not something I've looked into :/ Taking a glance it does look like helm3 has experimental OCI registry support.  If you have an idea into including it in this plugin, I'm definitely down to consider it/take contributions.  Otherwise I don't know of an other one that would support that yet.

**Comment by sherry-ummen** [comment]
Ok that's good to hear that you are open for pull request regarding this 🙂 I am no expert on golang, and did not find any instructions on how to build and run your code. Is it some standard way of running it which I can Google it or does it some different setup?. I have started to look into the code already. Thanks.

**Comment by sherry-ummen** [comment]
got it building and running the tests, now for my own learning I will make changes to support publish
